#!/usr/bin/env python3
"""Tests de bout en bout du SQL YOBBALEMA sur un PostgreSQL local (voir shim_supabase.sql).
Usage : python3 run_sql_tests.py   (en tant qu'utilisateur pouvant faire `su postgres`)"""
import subprocess, uuid, os, sys, time, threading, json

HERE = os.path.dirname(os.path.abspath(__file__))
SQL_DIR = os.path.dirname(HERE)
DB = "yobb_test"
PASS = FAIL = 0

def psql(script, db=DB, user_uid=None, role="authenticated", check=False):
    pre = ""
    if role:
        pre += f"set role {role};\n"
    if user_uid:
        pre += f"select set_config('request.jwt.claim.sub','{user_uid}',false) \\gset\n"
    p = subprocess.run(["su", "postgres", "-c", f"psql -d {db} -At -q -v ON_ERROR_STOP=1"],
                       input=pre + script, capture_output=True, text=True)
    return p.returncode, p.stdout.strip(), p.stderr.strip()

def admin(script):
    rc, out, err = psql(script, role=None)
    if rc != 0:
        print("ADMIN SQL ERROR:", err); sys.exit(1)
    return out

def ok(name, cond, detail=""):
    global PASS, FAIL
    if cond: PASS += 1; print(f"  PASS  {name}")
    else: FAIL += 1; print(f"  FAIL  {name}  {detail}")

def expect_ok(name, uid, sql):
    rc, out, err = psql(sql, user_uid=uid)
    ok(name, rc == 0, err[:300])
    return out

def expect_err(name, uid, sql, contains):
    rc, out, err = psql(sql, user_uid=uid)
    ok(name, rc != 0 and contains in err, f"(rc={rc}) {err[:300]}")

# ---------- base propre ----------
subprocess.run(["su", "postgres", "-c", f"psql -q -c 'drop database if exists {DB}'"], capture_output=True)
subprocess.run(["su", "postgres", "-c", f"psql -q -c 'create database {DB}'"], capture_output=True)
admin(open(os.path.join(HERE, "shim_supabase.sql")).read())
for f in ["01_schema_core.sql", "02_schema_rides_payments.sql", "03_schema_bus_delivery.sql",
          "04_rls_policies.sql", "05_services_config_security.sql", "06_service_functions.sql", "07_complements.sql", "08_paiements_penalites.sql"]:
    rc, out, err = psql(open(os.path.join(SQL_DIR, f)).read(), role=None)
    if rc != 0:
        print(f"ERREUR au chargement de {f}:\n{err}"); sys.exit(1)
print("Fichiers SQL 01 à 06 chargés sans erreur.\n")

def mkuser(label, role):
    u = str(uuid.uuid4())
    admin(f"insert into auth.users(id,email,raw_user_meta_data) values ('{u}','{label}@test.sn',"
          f"jsonb_build_object('prenom','{label}','nom','Test','telephone','+22177000000','role','{role}'))")
    return u

A = mkuser("Awa", "client");         B = mkuser("Bassirou", "chauffeur")
C = mkuser("Cheikh", "chauffeur");   D = mkuser("Demba", "chauffeur")
R = mkuser("Rokhaya", "receveur_bus"); M = mkuser("Moussa", "commercant")
A2 = mkuser("Fatou", "client"); R2 = mkuser("Ramatoulaye", "receveur_bus")
M2 = mkuser("Mariama", "commercant"); ADM = mkuser("Admin", "client")

# coordonnées (Dakar)
PLATEAU = (14.6708, -17.4382); OUAKAM = (14.7167, -17.4930)
B_POS = (14.6712, -17.4385)      # ~50 m du client
D_POS = (14.6816, -17.4382)      # ~1,2 km du client

print("== 1. Profils et confidentialité")
n = admin("select count(*) from profiles")
ok("trigger handle_new_user : 10 profils créés", n == "10", n)
roles = admin(f"select role from profiles where id='{B}'")
ok("rôle chauffeur pris depuis les métadonnées", roles == "chauffeur", roles)
expect_ok("client tente de se vérifier lui-même (ignoré)", A, f"update profiles set statut_verif='verifie', role='chauffeur', note_moyenne=5 where id='{A}'")
r = admin(f"select statut_verif||'/'||role||'/'||coalesce(note_moyenne::text,'null') from profiles where id='{A}'")
ok("statut_verif / rôle / note protégés contre l'auto-modification", r == "en_attente/client/null", r)
rc, out, err = psql(f"select count(*) from profiles where id='{B}'", user_uid=A)
ok("un client ne peut pas lire le profil (téléphone) d'un inconnu", out == "0", out)
rc, out, err = psql(f"select prenom from profils_publics where id='{B}'", user_uid=A)
ok("mais peut lire son profil public (prénom, note)", out == "Bassirou", out)

print("\n== 2. Véhicules et tarifs chauffeur")
for who, cat in [(B, "standard"), (C, "confort"), (D, "standard")]:
    expect_ok(f"véhicule {cat}", who, f"insert into vehicles(user_id,categorie,marque,modele,immatriculation) values ('{who}','{cat}','Toyota','Yaris','DK-000-AA')")
expect_err("tarif hors fourchette refusé (300 > 190)", B, f"insert into driver_pricing(driver_id,categorie,tarif_km_choisi) values ('{B}','standard',300)", "tarif_hors_fourchette")
expect_ok("tarif dans la fourchette accepté (160)", B, f"insert into driver_pricing(driver_id,categorie,tarif_km_choisi) values ('{B}','standard',160)")
expect_ok("tarif de D (140)", D, f"insert into driver_pricing(driver_id,categorie,tarif_km_choisi) values ('{D}','standard',140)")
avg = admin("select tarif_moyen from tarif_moyen_par_categorie where categorie='standard'")
ok("tarif moyen de la catégorie = 150", float(avg) == 150.0, avg)

print("\n== 3. Course à la demande + waxalé")
def ride_call(uid, offer="null", dist=9):
    return (f"select id from create_ride_request('standard','Plateau',{PLATEAU[0]},{PLATEAU[1]},"
            f"'Ouakam',{OUAKAM[0]},{OUAKAM[1]},{dist},{offer})")
expect_err("offre trop basse refusée", A, ride_call(A, "100"), "offre_trop_basse")
expect_err("catégorie moto refusée pour une course", A, f"select id from create_ride_request('moto','a',14.67,-17.43,'b',14.7,-17.4,5,null)", "categorie_invalide")
RIDE = expect_ok("création d'une course avec offre waxalé de 1000", A, ride_call(A, "1000"))
info = admin(f"select tarif_base||'|'||montant_offert||'|'||rayon_km||'|'||distance_km from ride_requests where id='{RIDE}'")
print("     ->", info)
tb, mo, ray, dk = info.split("|")
ok("tarif_base calculé côté serveur (multiple de 25, >= 500)", float(tb) >= 500 and float(tb) % 25 == 0, tb)
ok("rayon initial = 0,5 km", float(ray) == 0.5, ray)
expect_err("une seconde course active est refusée", A, ride_call(A, "null"), "course_deja_active")

def nearby(uid, pos):
    rc, out, err = psql(f"select count(*) from pending_rides_nearby({pos[0]},{pos[1]})", user_uid=uid)
    return out if rc == 0 else "ERR:" + err[:200]
ok("B (standard, à 50 m) voit la demande", nearby(B, B_POS) == "1", nearby(B, B_POS))
ok("C (véhicule confort) ne voit pas une demande standard", nearby(C, B_POS) == "0", nearby(C, B_POS))
ok("D (standard, à 1,2 km) ne la voit pas encore", nearby(D, D_POS) == "0", nearby(D, D_POS))
rc, out, err = psql(f"select prix_propose||'|'||votre_tarif||'|'||client_prenom from pending_rides_nearby({B_POS[0]},{B_POS[1]})", user_uid=B)
print("     ->", out)
ok("le chauffeur voit l'offre du client (1000)", out.startswith("1000"), out)
admin(f"update ride_requests set created_at = now() - interval '130 seconds' where id='{RIDE}'")
ok("après 130 s le rayon vaut 1,0 km : D (1,2 km) ne voit toujours pas", nearby(D, D_POS) == "0")
admin(f"update ride_requests set created_at = now() - interval '250 seconds' where id='{RIDE}'")
ok("après 250 s le rayon vaut 1,5 km : D voit la demande", nearby(D, D_POS) == "1", nearby(D, D_POS))
ok("un client ne peut pas appeler pending_rides_nearby", psql(f"select * from pending_rides_nearby(14.6,-17.4)", user_uid=A)[0] != 0)

print("\n== 4. Verrou atomique : deux chauffeurs valident en même temps")
res = {}
def acc(name, uid, delay, sleep):
    time.sleep(delay)
    sql = f"select id from accept_ride_request('{RIDE}');" + (f"select pg_sleep({sleep});" if sleep else "")
    res[name] = psql(sql, user_uid=uid)
t1 = threading.Thread(target=acc, args=("B", B, 0, 3))
t2 = threading.Thread(target=acc, args=("D", D, 1, 0))
t1.start(); t2.start(); t1.join(); t2.join()
b_ok = res["B"][0] == 0; d_ok = res["D"][0] == 0
ok("exactement UN chauffeur a obtenu la course", b_ok != d_ok, f"B={res['B'][2][:80]} D={res['D'][2][:80]}")
winner = admin(f"select driver_id from ride_requests where id='{RIDE}'")
ok("le premier arrivé (B) est le chauffeur assigné", winner == B, winner)
ok("le perdant reçoit 'course_indisponible'", "course_indisponible" in res["D"][2], res["D"][2][:120])

print("\n== 5. Écritures directes interdites (RLS)")
rc, out, err = psql(f"update ride_requests set statut='terminee' where id='{RIDE}' returning id", user_uid=A)
ok("le client ne peut pas modifier le statut directement", out == "", out)
rc, out, err = psql(f"update ride_requests set statut='terminee', montant_offert=1 where id='{RIDE}' returning id", user_uid=B)
ok("le chauffeur non plus (il doit passer par les fonctions)", out == "", out)
rc, out, err = psql(f"insert into payments(source_type,source_id,payeur_id,beneficiaire_id,moyen,montant) values ('ride','{RIDE}','{A}','{B}','especes',1)", user_uid=B)
ok("personne ne peut fabriquer un paiement", rc != 0, err[:100])
rc, out, err = psql(f"select prenom, telephone from profiles where id='{B}'", user_uid=A)
ok("après assignation, le client peut lire le profil du chauffeur", out.startswith("Bassirou"), out)
rc, out, err = psql(f"select count(*) from profiles where id='{A}'", user_uid=D)
ok("mais pas D, hors relation", out == "0", out)

print("\n== 6. Déroulé de la course + dette de commission")
expect_err("D ne peut pas démarrer la course de B", D, f"select * from demarrer_course('{RIDE}')", "course_introuvable")
expect_ok("B démarre", B, f"select * from demarrer_course('{RIDE}')")
expect_ok("B termine en espèces", B, f"select * from terminer_course('{RIDE}','especes')")
p = admin(f"select montant||'|'||commission_pct||'|'||moyen from payments where source_id='{RIDE}'")
ok("paiement = offre acceptée (1000), commission 5 %", p == "1000.00|5.00|especes", p)
dette = admin(f"select montant||'|'||regle from driver_ledger where driver_id='{B}'")
ok("dette de commission créée : 50 FCFA, non réglée", dette == "50.00|false", dette)
rc, out, err = psql("select mon_statut_chauffeur()", user_uid=B)
ok("B est bloqué", json.loads(out)["bloque"] is True, out)
RIDE2 = expect_ok("A commande une seconde course", A, ride_call(A, "null"))
expect_err("B bloqué ne peut plus accepter", B, f"select * from accept_ride_request('{RIDE2}')", "compte_bloque")
LED = json.loads(psql("select mon_statut_chauffeur()", user_uid=B)[1])["dettes"][0]["id"]
expect_err("un autre chauffeur ne peut pas régler la dette de B", D, f"select * from regler_dette('{LED}')", "dette_introuvable")
expect_ok("B règle sa dette (mode test)", B, f"select * from regler_dette('{LED}')")
expect_ok("B est débloqué et accepte la course", B, f"select * from accept_ride_request('{RIDE2}')")
expect_ok("B démarre", B, f"select * from demarrer_course('{RIDE2}')")
admin("update app_config set valeur='false' where cle='mode_test_paiements'")
admin("update app_config set valeur='' where cle='paiements_fournisseurs'")
expect_err("paiement Wave refusé si aucun fournisseur n'est activé", B, f"select * from terminer_course('{RIDE2}','wave')", "paiement_en_ligne_indisponible")
st = admin(f"select statut from ride_requests where id='{RIDE2}'")
ok("la course reste 'en_cours' après le refus", st == "en_cours", st)
admin("update app_config set valeur='wave,orange_money' where cle='paiements_fournisseurs'")
admin("update app_config set valeur='true' where cle='mode_test_paiements'")
expect_ok("Wave accepté en mode test", B, f"select * from terminer_course('{RIDE2}','wave')")
n = admin(f"select count(*) from driver_ledger where driver_id='{B}' and regle=false")
ok("paiement Wave = pas de dette", n == "0", n)
p = admin(f"select payeur_id from payments where source_id='{RIDE2}'")
rc, out, err = psql(f"select count(*) from payments", user_uid=D)
ok("D ne voit aucun paiement d'autrui", out == "0", out)
rc, out, err = psql(f"select count(*) from payments", user_uid=A)
ok("A voit ses 2 paiements", out == "2", out)

print("\n== 7. Avis")
expect_ok("A note B (5)", A, f"select * from noter('ride','{RIDE}',5::smallint,'Très bien')")
expect_err("double avis refusé", A, f"select * from noter('ride','{RIDE}',4::smallint,null)", "deja_note")
expect_err("D ne peut pas noter une course qui n'est pas la sienne", D, f"select * from noter('ride','{RIDE}',1::smallint,null)", "acces_refuse")
nm = admin(f"select note_moyenne from profiles where id='{B}'")
ok("note moyenne de B mise à jour = 5.0", nm == "5.0", nm)

print("\n== 8. Trajets interurbains")
B_VEH = admin(f"select id from vehicles where user_id='{B}'")
D_VEH = admin(f"select id from vehicles where user_id='{D}'")
def trip_sql(driver, veh, when="now() + interval '2 days'", places=3, prix=3000):
    return (f"insert into trips(driver_id,vehicle_id,depart_label,arrivee_label,depart_lat,depart_lng,arrivee_lat,arrivee_lng,"
            f"date_heure_depart,places_dispo,prix_place) values ('{driver}','{veh}','Dakar',"
            f"'Thiès',14.67,-17.43,14.79,-16.93,{when},{places},{prix}) returning id")
expect_err("un client ne peut pas publier un trajet", A, trip_sql(A, B_VEH), "acces_refuse")
expect_err("véhicule d'un autre refusé", B, trip_sql(B, D_VEH), "vehicule_invalide")
expect_err("date passée refusée", B, trip_sql(B, B_VEH, "now() - interval '1 hour'"), "date_passee")
TRIP = expect_ok("B publie un trajet Dakar → Thiès", B, trip_sql(B, B_VEH))
RES_A = expect_ok("A réserve 2 places", A, f"select id from reserver_trajet('{TRIP}',2::smallint)")
expect_err("A ne peut pas réserver deux fois", A, f"select * from reserver_trajet('{TRIP}',1::smallint)", "deja_reserve")
expect_err("B ne peut pas réserver son propre trajet", B, f"select * from reserver_trajet('{TRIP}',1::smallint)", "reservation_impossible")
RES_D = expect_ok("A2 réserve 2 places", A2, f"select id from reserver_trajet('{TRIP}',2::smallint)")
rc, out, err = psql(f"update reservations set statut='confirmee' where id='{RES_A}' returning id", user_uid=A)
ok("A ne peut pas se confirmer lui-même", out == "", out)
expect_err("A ne peut pas confirmer non plus via la fonction", A, f"select * from confirmer_reservation('{RES_A}')", "acces_refuse")
expect_ok("B confirme A (2 places)", B, f"select * from confirmer_reservation('{RES_A}')")
pl = admin(f"select places_dispo from trips where id='{TRIP}'")
ok("places restantes = 1", pl == "1", pl)
expect_err("confirmer A2 (2 places) alors qu'il n'en reste qu'1 échoue", B, f"select * from confirmer_reservation('{RES_D}')", "places_insuffisantes")
expect_ok("A annule sa réservation confirmée", A, f"select * from annuler_reservation('{RES_A}')")
pl = admin(f"select places_dispo from trips where id='{TRIP}'")
ok("places restaurées = 3", pl == "3", pl)
expect_ok("B confirme A2", B, f"select * from confirmer_reservation('{RES_D}')")
expect_err("encaisser avant la fin du trajet refusé", B, f"select * from encaisser_reservation('{RES_D}','especes')", "trajet_non_termine")
expect_ok("B termine le trajet", B, f"select * from terminer_trajet('{TRIP}')")
expect_ok("B encaisse A2 en espèces", B, f"select * from encaisser_reservation('{RES_D}','especes')")
expect_err("double encaissement refusé", B, f"select * from encaisser_reservation('{RES_D}','especes')", "deja_encaisse")
m = admin(f"select montant from payments where source_id='{RES_D}'")
ok("montant encaissé = 2 x 3000 = 6000", m == "6000.00", m)
d = admin(f"select montant from driver_ledger where driver_id='{B}' and regle=false")
ok("dette de commission 5 % = 300", d == "300.00", d)
expect_err("B (endetté) ne peut plus publier de trajet", B, trip_sql(B, B_VEH), "compte_bloque")
expect_ok("A2 note le trajet", A2, f"select * from noter('trip','{TRIP}',4::smallint,null)")
LED = json.loads(psql("select mon_statut_chauffeur()", user_uid=B)[1])["dettes"][0]["id"]
expect_ok("B règle", B, f"select * from regler_dette('{LED}')")

print("\n== 9. Bus TATA")
LINE_ROUTE = json.dumps([[14.7000, -17.4500], [14.7000, -17.4250], [14.7000, -17.4000]])
expect_err("un client ne peut pas créer de ligne de bus", A, f"insert into bus_lines(receveur_id,nom_ligne) values ('{A}','X')", "row-level security")
LINE = expect_ok("R crée la ligne 12 avec son tracé", R, f"insert into bus_lines(receveur_id,nom_ligne,terminus_depart,terminus_arrivee,trajet) values ('{R}','Ligne 12','Liberté 6','Petersen','{LINE_ROUTE}'::jsonb) returning id")
ok("tracé converti en géographie", admin(f"select trajet_geom is not null from bus_lines where id='{LINE}'") == "t")
expect_ok("R envoie la position du bus (20 km/h)", R, f"insert into bus_positions(bus_line_id,lat,lng,vitesse_estimee) values ('{LINE}',14.7000,-17.4500,20)")
rc, out, err = psql(f"insert into bus_positions(bus_line_id,lat,lng,vitesse_estimee) values ('{LINE}',14.7000,-17.4490,22) on conflict (bus_line_id, receveur_id) do update set lat=excluded.lat, lng=excluded.lng, vitesse_estimee=excluded.vitesse_estimee returning lng", user_uid=R)
ok("R met à jour la position par upsert (comme le site)", rc == 0 and float(out) == -17.449, err[:200] + out)
admin(f"update bus_positions set lat=14.7000, lng=-17.4500, vitesse_estimee=20 where bus_line_id='{LINE}'")
expect_err("A ne peut pas envoyer la position de ce bus", A, f"insert into bus_positions(bus_line_id,lat,lng) values ('{LINE}',14.7,-17.44)", "row-level security")
rc, out, err = psql("select statut||'|'||distance_m||'|'||eta_minutes from bus_arrivals(14.7002,-17.4200)", user_uid=A)
print("     ->", out)
st, dist, eta = out.split("|")
ok("client en aval du bus : statut 'approche'", st == "approche", out)
ok("distance le long du tracé ≈ 3,2 km", 3000 < float(dist) < 3500, dist)
ok("ETA ≈ 9-10 min à 20 km/h", 9 <= float(eta) <= 10.5, eta)
rc, out, err = psql("select statut from bus_arrivals(14.7002,-17.4400)", user_uid=A)
ok("client plus loin sur la ligne que le bus : 'approche'", out == "approche", out)
admin(f"update bus_positions set lat=14.7000, lng=-17.4100 where bus_line_id='{LINE}'")
rc, out, err = psql("select statut||'|'||coalesce(eta_minutes::text,'null') from bus_arrivals(14.7002,-17.4400)", user_uid=A)
ok("bus déjà passé devant le client : statut 'passe', pas d'ETA", out == "passe|null", out)
admin(f"update bus_positions set lat=14.7000, lng=-17.4500 where bus_line_id='{LINE}'")
rc, out, err = psql("select count(*) from bus_arrivals(14.7500,-17.4200)", user_uid=A)
ok("client loin du tracé : aucune ligne proposée", out == "0", out)
admin(f"update bus_positions set updated_at = now() - interval '5 minutes' where bus_line_id='{LINE}'")
rc, out, err = psql("select count(*) from bus_arrivals(14.7002,-17.4200)", user_uid=A)
ok("position périmée (> 2 min) : bus masqué", out == "0", out)
admin(f"update bus_positions set updated_at = now() where bus_line_id='{LINE}'")
rc, out, err = psql("select count(*) from bus_arrivals(14.7002,-17.4200)", role="anon")
ok("visiteur NON connecté peut consulter les bus (service public gratuit)", rc == 0 and out == "1", err[:150] + out)
rc, out, err = psql("select count(*) from pending_rides_nearby(14.67,-17.43)", role="anon")
ok("mais pas les demandes de course (réservé aux chauffeurs)", rc != 0, out)

print("\n== 10. Livraison simple et marchande (pharmacie)")
expect_err("un client ne peut pas créer de commerce", A, "insert into merchants(owner_id,type,nom_commerce,lat,lng) values ('"+A+"','pharmacie','X',14.67,-17.43)", "row-level security")
MER = expect_ok("M crée sa pharmacie", M, f"insert into merchants(owner_id,type,nom_commerce,lat,lng,statut_verif) values ('{M}','pharmacie','Pharmacie Liberté',14.6790,-17.4400,'verifie') returning id")
sv = admin(f"select statut_verif from merchants where id='{MER}'")
ok("un commerçant ne peut pas se déclarer 'verifie' (forcé à en_attente)", sv == "en_attente", sv)
expect_err("commande pharmacie sans ordonnance refusée", A, f"select * from create_delivery_order('pharmacie','Domicile',14.6720,-17.4390)", "ordonnance_manquante")
expect_err("ordonnance d'un autre utilisateur refusée", A, f"select * from create_delivery_order('pharmacie','Domicile',14.6720,-17.4390,null,null,null,null,null,'{B}/x.jpg')", "ordonnance_manquante")
DEL = expect_ok("A commande des médicaments (ordonnance jointe)", A, f"select id from create_delivery_order('pharmacie','Domicile',14.6720,-17.4390,null,null,null,null,null,'{A}/ordo1.jpg')")
s = admin(f"select statut||'|'||collecte_label from delivery_orders where id='{DEL}'")
ok("commerçant le plus proche choisi automatiquement, statut en_attente_devis", s == "en_attente_devis|Pharmacie Liberté", s)
rc, out, err = psql(f"select count(*) from delivery_orders", user_uid=D)
ok("D (étranger à la commande) ne la voit pas", out == "0", out)
rc, out, err = psql(f"select count(*) from delivery_orders", user_uid=M)
ok("le commerçant la voit", out == "1", out)
LIG = '[{"libelle":"Paracétamol 500mg","prix":850},{"libelle":"Amoxicilline 1g","prix":2400}]'
expect_err("un client ne peut pas envoyer de devis", A, f"select * from envoyer_devis('{DEL}','{LIG}'::jsonb,700)", "acces_refuse")
expect_err("devis vide refusé", M, f"select * from envoyer_devis('{DEL}','[]'::jsonb,700)", "devis_vide")
expect_ok("M envoie le devis (2 lignes + livraison 700)", M, f"select * from envoyer_devis('{DEL}','{LIG}'::jsonb,700,'Prêt dans 10 min')")
dv = admin(f"select montant_produits||'|'||montant_livraison||'|'||statut from delivery_orders where id='{DEL}'")
ok("total produits = 3250, livraison = 700, statut devis_envoye", dv == "3250.00|700.00|devis_envoye", dv)
rc, out, err = psql(f"select count(*) from pending_deliveries_nearby(14.6790,-17.4400)", user_uid=B)
ok("pas visible des livreurs avant approbation du client", out == "0", out)
expect_err("un autre client ne peut pas approuver le devis", A2, f"select * from approuver_devis('{DEL}')", "devis_introuvable")
expect_ok("A approuve le devis", A, f"select * from approuver_devis('{DEL}')")
rc, out, err = psql(f"select count(*) from pending_deliveries_nearby(14.6795,-17.4405)", user_uid=B)
ok("B (à ~70 m de la pharmacie) voit la livraison", out == "1", out)
expect_ok("B accepte la livraison", B, f"select * from accept_delivery_order('{DEL}')")
expect_err("D ne peut pas accepter une livraison déjà prise", D, f"select * from accept_delivery_order('{DEL}')", "livraison_indisponible")
expect_err("commande marchande en espèces refusée", B, f"select * from terminer_livraison('{DEL}','especes')", "paiement_en_ligne_requis")
rc, out, err = psql(f"select categorie_montant||':'||beneficiaire_id||':'||montant from terminer_livraison('{DEL}','wave') order by 1", user_uid=B)
lines = out.split("\n")
ok("2 paiements distincts créés", len(lines) == 2, out)
ok("produits (3250) → commerçant M", any(l == f"produits:{M}:3250.00" for l in lines), out)
ok("livraison (700) → livreur B", any(l == f"livraison:{B}:700.00" for l in lines), out)
st = admin(f"select statut from delivery_orders where id='{DEL}'")
ok("livraison marquée 'livree'", st == "livree", st)
n = admin(f"select count(*) from driver_ledger where regle=false")
ok("aucune dette (paiement en ligne)", n == "0", n)
COL = expect_ok("A commande un colis (livraison simple)", A, "select id from create_delivery_order('colis','Almadies',14.7450,-17.5000,'Plateau',14.6708,-17.4382,10,'Carton',null,'moto')")
s = admin(f"select statut||'|'||montant_livraison from delivery_orders where id='{COL}'")
print("     ->", s)
ok("colis : approuvé directement, prix calculé sur la distance", s.startswith("approuvee|") and float(s.split('|')[1]) >= 500, s)
rc, out, err = psql(f"select count(*) from pending_deliveries_nearby(14.6708,-17.4382)", user_uid=B)
ok("colis 'moto' invisible pour B (voiture)", out == "0", out)
expect_ok("D ajoute une moto", D, f"insert into vehicles(user_id,categorie) values ('{D}','moto')")
rc, out, err = psql(f"select count(*) from pending_deliveries_nearby(14.6708,-17.4382)", user_uid=D)
ok("colis 'moto' visible pour D (moto)", out == "1", out)
expect_ok("D accepte", D, f"select * from accept_delivery_order('{COL}')")
expect_ok("D termine en espèces", D, f"select * from terminer_livraison('{COL}','especes')")
n = admin(f"select montant from driver_ledger where driver_id='{D}' and regle=false")
ok("dette de commission de D créée (5 % du prix de livraison)", n != "", n)

print("\n== 11. Vérification d'identité obligatoire (réglage verification_requise)")
admin("update app_config set valeur='true' where cle='verification_requise'")
RIDE3 = expect_ok("A2 commande une course", A2, ride_call(A2, "null"))
expect_err("C non vérifié (confort) / B non vérifié ne peut pas accepter", B, f"select * from accept_ride_request('{RIDE3}')", "compte_non_verifie")
admin(f"update profiles set statut_verif='verifie' where id='{B}'")
expect_ok("après vérification par l'administrateur, B accepte", B, f"select * from accept_ride_request('{RIDE3}')")
admin("update app_config set valeur='false' where cle='verification_requise'")

print("\n== 12. Sécurité des fonctions sensibles")
expect_err("un chauffeur ne peut pas appeler regler_dette_admin", B, f"select * from regler_dette_admin(gen_random_uuid())", "permission denied")
expect_err("ni _creer_paiement directement", B, f"select * from _creer_paiement('ride',gen_random_uuid(),'trajet',null,null,'especes',1)", "permission denied")
rc, out, err = psql("select cle from app_config limit 1", user_uid=A)
ok("config lisible par les utilisateurs connectés", rc == 0 and out != "", err)
rc, out, err = psql("update app_config set valeur='0' where cle='commission_pct' returning cle", user_uid=B)
ok("mais modifiable par personne côté client", out == "", out)
rc, out, err = psql("update pricing_config set tarif_km_base=1 returning id", user_uid=B)
ok("les tarifs ne se modifient pas côté client", out == "", out)


print("\n== 13. Notifications")
def ntypes(uid):
    rc, out, err = psql("select coalesce(string_agg(distinct type, ','), '') from notifications", user_uid=uid)
    return set(out.split(",")) if out else set()
ta = ntypes(A)
for t in ["course_acceptee", "course_terminee", "reservation_confirmee", "devis_recu", "livraison_en_route", "livraison_terminee"]:
    ok(f"A a reçu « {t} »", t in ta, str(ta))
tb = ntypes(B)
for t in ["reservation_nouvelle", "dette_creee", "dette_reglee", "avis_recu"]:
    ok(f"le chauffeur B a reçu « {t} »", t in tb, str(tb))
ok("le commerçant M a reçu « commande_nouvelle » et « devis_valide »", {"commande_nouvelle", "devis_valide"} <= ntypes(M), str(ntypes(M)))
rc, out, err = psql(f"select count(*) from notifications where user_id <> '{D}'", user_uid=D)
ok("D ne voit que ses propres notifications", out == "0", out)
rc, out, err = psql(f"insert into notifications(user_id,type,titre) values ('{A}','x','faux')", user_uid=A)
ok("un utilisateur ne peut pas fabriquer une notification", rc != 0, err[:80])
rc, out, err = psql("select notifications_marquer_lues()", user_uid=A)
ok("marquer comme lues renvoie un nombre > 0", rc == 0 and int(out) > 0, out + err)
rc, out, err = psql("select count(*) from notifications where lu = false", user_uid=A)
ok("plus aucune notification non lue", out == "0", out)
rc, out, err = psql("select notifications_marquer_lues()", user_uid=A)
ok("l'opération est idempotente (0)", out == "0", out)

print("\n== 14. Position en direct des chauffeurs")
expect_ok("B publie sa position", B, f"insert into driver_locations(driver_id,lat,lng,vitesse_kmh) values ('{B}',14.671,-17.438,25) on conflict (driver_id) do update set lat=excluded.lat, lng=excluded.lng, vitesse_kmh=excluded.vitesse_kmh")
expect_ok("B met à jour (upsert)", B, f"insert into driver_locations(driver_id,lat,lng,vitesse_kmh) values ('{B}',14.672,-17.439,30) on conflict (driver_id) do update set lat=excluded.lat, lng=excluded.lng, vitesse_kmh=excluded.vitesse_kmh")
rc, out, err = psql("select count(*) from driver_locations", user_uid=A2)
ok("A2 (client de la course assignée à B) voit la position de B", out == "1", out)
rc, out, err = psql("select count(*) from driver_locations", user_uid=A)
ok("A (sans course en cours avec B) ne la voit pas", out == "0", out)
rc, out, err = psql("select count(*) from driver_locations", user_uid=D)
ok("D non plus", out == "0", out)
rc, out, err = psql(f"insert into driver_locations(driver_id,lat,lng) values ('{A}',14.6,-17.4)", user_uid=A)
ok("un client ne peut pas se déclarer chauffeur localisé", rc != 0, err[:80])
rc, out, err = psql(f"insert into driver_locations(driver_id,lat,lng) values ('{B}',0,0) on conflict (driver_id) do update set lat=0", user_uid=D)
ok("D ne peut pas écrire la position de B", rc != 0, out)
expect_ok("B supprime sa position (hors ligne)", B, "delete from driver_locations")
rc, out, err = psql("select count(*) from driver_locations", user_uid=A2)
ok("la position a disparu pour le client", out == "0", out)

print("\n== 15. Bus : plusieurs bus par ligne + recherche par trajet")
expect_ok("R2 fait circuler un 2e bus sur la ligne de R", R2, f"insert into bus_positions(bus_line_id,lat,lng,vitesse_estimee,bus_label) values ('{LINE}',14.7000,-17.4300,30,'Bus 2 - DK 4455')")
admin(f"update bus_positions set updated_at = now() where bus_line_id='{LINE}'")
ok("la ligne compte maintenant 2 positions", admin(f"select count(*) from bus_positions where bus_line_id='{LINE}'") == "2")
rc, out, err = psql("select count(distinct bus_id) from bus_arrivals(14.7002,-17.4200)", user_uid=A)
ok("bus_arrivals renvoie 2 bus distincts pour la ligne", out == "2", out + err)
rc, out, err = psql(f"update bus_positions set lat=0 where receveur_id='{R}' returning id", user_uid=R2)
ok("R2 ne peut pas déplacer le bus de R", out == "", out)
rc, out, err = psql(f"insert into bus_positions(bus_line_id,lat,lng) values ('{LINE}',14.7,-17.44)", user_uid=A)
ok("un client ne peut pas ajouter un bus", rc != 0, out)
rc, out, err = psql("select bus_label||'|'||statut||'|'||eta_minutes from bus_trajet(14.7002,-17.42,14.7002,-17.41) order by eta_minutes limit 1", user_uid=A)
ok("bus_trajet : le bus le plus proche est le bus 2 (approche)", out.startswith("Bus 2 - DK 4455|approche|"), out + err)
rc, out, err = psql("select count(*) from bus_trajet(14.7002,-17.42,14.7002,-17.41) where statut='approche'", user_uid=A)
ok("bus_trajet : 2 bus approchent", out == "2", out)
rc, out, err = psql("select distance_trajet_m from bus_trajet(14.7002,-17.42,14.7002,-17.41) limit 1", user_uid=A)
ok("bus_trajet : distance à bord ≈ 1,1 km", 1000 < float(out) < 1200, out + err)
rc, out, err = psql("select duree_trajet_min from bus_trajet(14.7002,-17.42,14.7002,-17.41) order by vitesse_kmh desc limit 1", user_uid=A)
ok("bus_trajet : durée à bord ≈ 2 min à 30 km/h", 1.9 < float(out) < 2.4, out + err)
rc, out, err = psql("select count(*) from bus_trajet(14.7002,-17.41,14.7002,-17.42)", user_uid=A)
ok("bus_trajet : sens inverse = aucune ligne", out == "0", out)
rc, out, err = psql("select count(*) from bus_trajet(14.7002,-17.42,14.95,-17.41)", user_uid=A)
ok("bus_trajet : destination hors ligne = aucune ligne", out == "0", out)
rc, out, err = psql("select string_agg(distinct statut, ',') from bus_trajet(14.7002,-17.44,14.7002,-17.41)", user_uid=A)
ok("bus_trajet : bus déjà passé signalé « passe »", "passe" in out and "approche" in out, out)
L2 = expect_ok("R crée une 2e ligne sans bus", R, f"insert into bus_lines(receveur_id,nom_ligne,terminus_depart,terminus_arrivee,trajet) values ('{R}','Ligne 8','A','B','[[14.72,-17.45],[14.72,-17.40]]'::jsonb) returning id")
rc, out, err = psql("select statut from bus_trajet(14.7202,-17.44,14.7202,-17.42)", role="anon")
ok("ligne sans bus actif : statut « aucun_bus » (accessible sans connexion)", out == "aucun_bus", out + err)

print("\n== 16. Avis livraison / commerçant")
expect_ok("A note le livreur B (livraison)", A, f"select * from noter('delivery','{DEL}',5::smallint,'Rapide')")
expect_ok("B note le client A (livraison)", B, f"select * from noter('delivery','{DEL}',4::smallint,null)")
expect_ok("A note le commerçant M", A, f"select * from noter('commerce','{DEL}',5::smallint,'Service impeccable')")
expect_err("D ne peut pas noter cette livraison", D, f"select * from noter('delivery','{DEL}',1::smallint,null)", "acces_refuse")
expect_err("le livreur ne peut pas noter le commerçant", B, f"select * from noter('commerce','{DEL}',1::smallint,null)", "acces_refuse")
expect_err("double avis refusé", A, f"select * from noter('commerce','{DEL}',3::smallint,null)", "deja_note")
expect_err("pas d'avis « commerce » sur un colis sans commerçant", A, f"select * from noter('commerce','{COL}',3::smallint,null)", "avis_impossible")
ok("note moyenne du commerçant M = 5.0", admin(f"select note_moyenne from profiles where id='{M}'") == "5.0")
ok("note moyenne de A (avis du livreur) = 4.0", admin(f"select note_moyenne from profiles where id='{A}'") == "4.0")
ok("note moyenne de B = moyenne de 3 avis (5, 4, 5) = 4.7", admin(f"select note_moyenne from profiles where id='{B}'") == "4.7")
RIDE4 = expect_ok("A commande une course", A, ride_call(A, "null"))
rc, out, err = psql(f"select client_note from pending_rides_nearby({PLATEAU[0]},{PLATEAU[1]})", user_uid=B)
ok("le chauffeur voit la note du client (4.0) avant d'accepter", out.strip() == "4.0", out + err)
expect_ok("A annule", A, f"select * from annuler_course('{RIDE4}')")

print("\n== 17. Repli sur le commerçant suivant + expirations")
MER2 = expect_ok("M2 crée une 2e pharmacie (plus éloignée)", M2, f"insert into merchants(owner_id,type,nom_commerce,lat,lng) values ('{M2}','pharmacie','Pharmacie Médina',14.6900,-17.4500) returning id")
def order_pharma(uid=A):
    return expect_ok("A commande des médicaments", uid, f"select id from create_delivery_order('pharmacie','Domicile',14.6720,-17.4390,null,null,null,null,null,'{uid}/o.jpg')")
OR2 = order_pharma()
ok("commande d'abord adressée à la pharmacie la plus proche (M)", admin(f"select merchant_id from delivery_orders where id='{OR2}'") == MER)
expect_ok("M refuse la commande", M, f"select * from refuser_commande('{OR2}')")
r = admin(f"select statut||'|'||merchant_id||'|'||collecte_label||'|'||(merchants_ecartes @> array['{MER}']::uuid[]) from delivery_orders where id='{OR2}'")
ok("elle est transmise à la pharmacie suivante (M2), M est écarté", r == f"en_attente_devis|{MER2}|Pharmacie Médina|true", r)
ok("M2 est notifié d'une nouvelle commande", "commande_nouvelle" in ntypes(M2), str(ntypes(M2)))
ok("le client est prévenu du changement de partenaire", "commande_reattribuee" in ntypes(A), str(ntypes(A)))
expect_err("M ne peut plus agir sur cette commande", M, f"select * from refuser_commande('{OR2}')", "commande_introuvable")
expect_ok("M2 refuse à son tour", M2, f"select * from refuser_commande('{OR2}')")
r = admin(f"select statut||'|'||motif_annulation from delivery_orders where id='{OR2}'")
ok("plus personne : commande annulée avec un motif clair", r == "annulee|Aucun partenaire disponible pour cette commande.", r)
rc, out, err = psql("select titre||'|'||corps from notifications where type='commande_annulee' order by created_at desc limit 1", user_uid=A)
ok("le client reçoit le motif de l'annulation", "Aucun partenaire disponible" in out, out + err)

OR3 = order_pharma()
admin(f"update delivery_orders set commerce_assigne_at = now() - interval '10 minutes' where id='{OR3}'")
expect_ok("expiration : le commerçant M ne répond pas", A, "select expire_stale_deliveries()")
ok("commande transmise à M2 après le délai", admin(f"select merchant_id from delivery_orders where id='{OR3}'") == MER2)
admin(f"update delivery_orders set commerce_assigne_at = now() - interval '10 minutes' where id='{OR3}'")
expect_ok("M2 ne répond pas non plus", A, "select expire_stale_deliveries()")
r = admin(f"select statut||'|'||motif_annulation from delivery_orders where id='{OR3}'")
ok("commande annulée : « aucun partenaire n'a répondu »", r.startswith("annulee|Aucun partenaire n"), r)

OR4 = order_pharma()
expect_ok("M envoie un devis", M, f"select * from envoyer_devis('{OR4}','[{{\"libelle\":\"Doliprane\",\"prix\":700}}]'::jsonb,500)")
ok("le devis est valable 30 minutes", admin(f"select devis_expire_at > now() + interval '25 minutes' from delivery_orders where id='{OR4}'") == "t")
admin(f"update delivery_orders set devis_expire_at = now() - interval '1 minute' where id='{OR4}'")
expect_ok("expiration du devis", A, "select expire_stale_deliveries()")
r = admin(f"select statut||'|'||motif_annulation from delivery_orders where id='{OR4}'")
ok("devis non validé à temps : commande annulée", r == "annulee|Le devis a expiré sans validation.", r)
expect_err("on ne peut plus valider un devis expiré", A, f"select * from approuver_devis('{OR4}')", "devis_introuvable")

print("\n== 18. Modifier un trajet publié")
TRIP2 = expect_ok("B publie un trajet", B, trip_sql(B, B_VEH))
expect_ok("modification libre tant qu'aucune réservation (prix 3500, 4 places)", B, f"select * from modifier_trajet('{TRIP2}',3500,now() + interval '3 days',4::smallint)")
ok("prix et places mis à jour", admin(f"select prix_place||'|'||places_dispo from trips where id='{TRIP2}'") == "3500.00|4")
expect_err("un autre chauffeur ne peut pas modifier", D, f"select * from modifier_trajet('{TRIP2}',1000,now() + interval '3 days',4::smallint)", "trajet_introuvable")
expect_err("date passée refusée", B, f"select * from modifier_trajet('{TRIP2}',3500,now() - interval '1 day',4::smallint)", "date_passee")
RES2 = expect_ok("A2 réserve 2 places", A2, f"select id from reserver_trajet('{TRIP2}',2::smallint)")
expect_err("prix figé dès qu'une réservation existe", B, f"select * from modifier_trajet('{TRIP2}',2000,now() + interval '3 days',4::smallint)", "modification_impossible")
expect_ok("B confirme", B, f"select * from confirmer_reservation('{RES2}')")
expect_err("moins de places que de places confirmées refusé", B, f"select * from modifier_trajet('{TRIP2}',3500,(select date_heure_depart from trips where id='{TRIP2}'),1::smallint)", "places_invalides")
expect_ok("augmenter le nombre total de places reste possible (6)", B, f"select * from modifier_trajet('{TRIP2}',3500,(select date_heure_depart from trips where id='{TRIP2}'),6::smallint)")
ok("places restantes = 6 - 2 confirmées = 4", admin(f"select places_dispo from trips where id='{TRIP2}'") == "4")

print("\n== 19. Administration")
expect_err("un utilisateur ordinaire ne peut pas lire les statistiques", A, "select admin_stats()", "acces_refuse")
rc, out, err = psql(f"insert into admins(user_id) values ('{A}')", user_uid=A)
ok("personne ne peut s'ajouter aux administrateurs via l'API", rc != 0, out)
admin(f"insert into admins(user_id) values ('{ADM}')")
rc, out, err = psql("select admin_stats()", user_uid=ADM)
st = json.loads(out) if rc == 0 else {}
ok("admin_stats() renvoie les indicateurs", rc == 0 and st.get("courses_terminees", 0) >= 2 and "utilisateurs" in st and "dettes_en_cours" in st, out[:200] + err)
print("     ->", {k: st.get(k) for k in ("courses_terminees", "livraisons_livrees", "commissions_generees", "dettes_en_cours", "chauffeurs_bloques")})
rc, out, err = psql("select count(*) from profiles", user_uid=ADM)
n_adm = int(out or 0)
rc, out, err = psql("select count(*) from profiles", user_uid=A)
ok("l'admin voit tous les profils, un utilisateur non", n_adm == 10 and int(out) < n_adm, f"admin={n_adm} user={out}")
rc, out, err = psql("select count(*) from driver_ledger", user_uid=ADM)
ok("l'admin voit le registre des dettes", int(out) >= 1, out + err)
rc, out, err = psql("select count(*) from driver_ledger", user_uid=A)
ok("un utilisateur ordinaire non", out == "0", out)

expect_err("un utilisateur ne peut pas vérifier un compte", A, f"select * from admin_set_verification('{A2}','verifie')", "acces_refuse")
expect_ok("l'admin vérifie A2", ADM, f"select * from admin_set_verification('{A2}','verifie')")
ok("statut passé à « verifie »", admin(f"select statut_verif from profiles where id='{A2}'") == "verifie")
ok("A2 est notifié « compte_verifie »", "compte_verifie" in ntypes(A2), str(ntypes(A2)))
expect_ok("l'admin rejette A2", ADM, f"select * from admin_set_verification('{A2}','rejete')")
ok("A2 est notifié « compte_rejete »", "compte_rejete" in ntypes(A2), str(ntypes(A2)))
expect_ok("l'admin vérifie la pharmacie M", ADM, f"select * from admin_set_merchant_verification('{MER}','verifie')")
ok("statut du commerce = verifie (la protection ne bloque pas l'admin)", admin(f"select statut_verif from merchants where id='{MER}'") == "verifie")
ok("M est notifié « commerce_verifie »", "commerce_verifie" in ntypes(M), str(ntypes(M)))

LEDD = admin(f"select id from driver_ledger where driver_id='{D}' and regle=false limit 1")
expect_err("un chauffeur ne peut pas effacer une dette via admin_regler_dette", D, f"select * from admin_regler_dette('{LEDD}')", "acces_refuse")
expect_ok("l'admin règle la dette de D", ADM, f"select * from admin_regler_dette('{LEDD}')")
ok("D est notifié « dette_reglee »", "dette_reglee" in ntypes(D), str(ntypes(D)))

expect_ok("l'admin modifie un paramètre", ADM, "select * from admin_set_config('tarif_minimum','600')")
ok("valeur enregistrée", admin("select valeur from app_config where cle='tarif_minimum'") == "600")
expect_ok("… et le remet", ADM, "select * from admin_set_config('tarif_minimum','500')")
expect_err("paramètre inconnu refusé", ADM, "select * from admin_set_config('nimporte_quoi','1')", "parametre_inconnu")
expect_err("un utilisateur ne peut pas modifier la configuration", A, "select * from admin_set_config('tarif_minimum','1')", "acces_refuse")
expect_err("tarif incohérent refusé (minimum > base)", ADM, "select * from admin_set_pricing('standard',200,190,150)", "tarif_invalide")
expect_ok("tarif cohérent accepté", ADM, "select * from admin_set_pricing('standard',130,190,150)")

admin(f"insert into storage.objects(bucket_id,name) values ('documents','{A}/cni.jpg')")
rc, out, err = psql("select count(*) from storage.objects where bucket_id='documents'", user_uid=ADM)
ok("l'admin peut lire les pièces d'identité (Storage)", out == "1", out + err)
rc, out, err = psql("select count(*) from storage.objects where bucket_id='documents'", user_uid=D)
ok("un autre utilisateur non", out == "0", out)
rc, out, err = psql("select count(*) from storage.objects where bucket_id='documents'", user_uid=A)
ok("le propriétaire voit sa propre pièce", out == "1", out)


# ===================================================================== 20+
def real_ride(driver, moyen):
    rid = expect_ok("A commande une course", A, ride_call(A, "null"))
    expect_ok("le chauffeur accepte", driver, f"select * from accept_ride_request('{rid}')")
    expect_ok("le chauffeur démarre", driver, f"select * from demarrer_course('{rid}')")
    expect_ok(f"le chauffeur termine ({moyen})", driver, f"select * from terminer_course('{rid}','{moyen}')")
    return rid
def pay_status(ref_id):
    return admin(f"select string_agg(statut_transaction, ',' order by categorie_montant) from payments where source_id='{ref_id}'")
def new_intent(uid, source, sid, prov="wave"):
    rc, out, err = psql(f"select id||'|'||ref_courte||'|'||montant||'|'||statut from demander_paiement('{source}','{sid}','{prov}')", user_uid=uid)
    return (out.split("|") if rc == 0 else None), err
def confirm(ref, statut, montant="null", pref="null", detail="null"):
    q = lambda v: v if v == "null" else f"'{v}'"
    return admin(f"select statut||'|'||coalesce(detail,'') from confirmer_intent('{ref}','{statut}',{montant},{q(pref)},{q(detail)})")

print("\n== 20. Paiements en ligne (mode réel)")
admin("update app_config set valeur='false' where cle='mode_test_paiements'")
R5 = real_ride(D, "wave")
ok("paiement Wave en mode réel : EN ATTENTE (pas confirmé d'office)", pay_status(R5) == "en_attente", pay_status(R5))
ok("la course, elle, est bien terminée", admin(f"select statut from ride_requests where id='{R5}'") == "terminee")
rc, out, err = psql("select (mon_solde()->>'en_attente_de_paiement')::numeric > 0", user_uid=D)
ok("le chauffeur voit ce montant « en attente de paiement »", out == "t", out + err)
expect_err("le chauffeur (bénéficiaire) ne peut pas déclencher le paiement", D, f"select * from demander_paiement('ride','{R5}','wave')", "aucun_paiement_du")
expect_err("espèces refusé pour un paiement en ligne", A, f"select * from demander_paiement('ride','{R5}','especes')", "paiement_en_ligne_indisponible")
admin("update app_config set valeur='true' where cle='mode_test_paiements'")
expect_err("en mode test : paiement simulé, pas de tentative", A, f"select * from demander_paiement('ride','{R5}','wave')", "paiement_simule")
admin("update app_config set valeur='false' where cle='mode_test_paiements'")
i1, err = new_intent(A, "ride", R5, "wave")
ok("A crée une tentative de paiement (statut « cree »)", i1 and i1[3] == "cree", str(err))
ok("montant de la tentative = montant dû", i1 and float(i1[2]) == float(admin(f"select montant from payments where source_id='{R5}'")))
i2, err = new_intent(A, "ride", R5, "orange_money")
ok("une nouvelle tentative remplace la précédente", admin(f"select statut from payment_intents where id='{i1[0]}'") == "expire")
ok("le moyen du paiement suit le choix du client (Orange Money)", admin(f"select moyen from payments where source_id='{R5}'") == "orange_money")
expect_err("un client ne peut pas confirmer un paiement lui-même", A, f"select * from confirmer_intent('{i2[1]}','reussi',null,null,null)", "permission denied")
rc, out, err = psql("select count(*) from payment_intents", user_uid=D)
ok("un tiers ne voit pas les tentatives de paiement d'autrui", out == "0", out)
r = confirm(i2[1], "reussi", i2[2], "OM-TXN-1")
ok("le webhook confirme : tentative « reussi »", r.startswith("reussi|"), r)
ok("paiement passé à « confirme » avec la référence de l'opérateur", admin(f"select statut_transaction||'|'||reference_externe from payments where source_id='{R5}'") == "confirme|OM-TXN-1")
ok("le chauffeur est notifié « paiement_recu », le client « paiement_confirme »", "paiement_recu" in ntypes(D) and "paiement_confirme" in ntypes(A))
n_before = admin(f"select count(*) from notifications where type='paiement_confirme' and user_id='{A}'")
r = confirm(i2[1], "reussi", i2[2], "OM-TXN-1")
ok("rejeu du webhook : rien n'est refait (idempotent)", admin(f"select count(*) from notifications where type='paiement_confirme' and user_id='{A}'") == n_before)

R6 = real_ride(D, "wave")
i, _ = new_intent(A, "ride", R6)
r = confirm(i[1], "reussi", "1", "W-1")
ok("montant incohérent : rien n'est confirmé, anomalie signalée", "montant_incoherent" in r and pay_status(R6) == "en_attente", r)
r = confirm(i[1], "reussi", i[2], "W-1")
ok("puis le bon montant : confirmé", pay_status(R6) == "confirme" and r.startswith("reussi|"), r)

R7 = real_ride(D, "wave")
i, _ = new_intent(A, "ride", R7)
r = confirm(i[1], "echoue", "null", "null", "annulé par le client")
ok("échec de paiement : tentative « echoue », paiement toujours dû", r.startswith("echoue|") and pay_status(R7) == "en_attente", r)
ok("le client est notifié de l'échec", "paiement_echoue" in ntypes(A))
i_old, _ = new_intent(A, "ride", R7, "wave")
i_new, _ = new_intent(A, "ride", R7, "orange_money")
confirm(i_new[1], "reussi", i_new[2], "OM-NEW")
r = confirm(i_old[1], "reussi", i_old[2], "WAVE-LATE")
ok("paiement tardif d'une ancienne tentative : signalé « doublon », pas de double encaissement",
   "doublon" in r and admin(f"select count(*) from payments where source_id='{R7}' and statut_transaction='confirme'") == "1", r)
ok("l'anomalie est comptée dans les statistiques admin", json.loads(psql("select admin_stats()", user_uid=ADM)[1]).get("anomalies_paiement", 0) >= 1)
i, _ = new_intent(A, "ride", real_ride(D, "wave"))
admin(f"update payment_intents set expires_at = now() - interval '1 minute' where id='{i[0]}'")
rc, out, err = psql("select expire_stale_payments()", user_uid=A)
ok("expiration des tentatives non abouties", rc == 0 and int(out) >= 1, out + err)
ok("… statut « expire »", admin(f"select statut from payment_intents where id='{i[0]}'") == "expire")

print("\n== 21. Déduction automatique de la dette")
R10 = real_ride(D, "wave")
i10, _ = new_intent(A, "ride", R10)
R11 = real_ride(D, "especes")
debt = admin(f"select montant from driver_ledger where driver_id='{D}' and regle=false")
ok("D a une dette de commission (course en espèces)", debt != "", debt)
rc, out, err = psql("select mon_statut_chauffeur()", user_uid=D)
ok("D est bloqué", json.loads(out)["bloque"] is True)
confirm(i10[1], "reussi", i10[2], "TXN-10")
ok("le paiement numérique confirmé règle la dette AUTOMATIQUEMENT", admin(f"select count(*) from driver_ledger where driver_id='{D}' and regle=true and regle_type='auto'") != "0" and admin(f"select count(*) from driver_ledger where driver_id='{D}' and regle=false") == "0")
rc, out, err = psql("select mon_statut_chauffeur()", user_uid=D)
ok("D est débloqué sans rien faire", json.loads(out)["bloque"] is False)
rc, out, err = psql("select mon_solde()", user_uid=D)
sol = json.loads(out)
ok("mon_solde() : dette déduite = montant de la dette", float(sol["dettes_deduites"]) == float(debt), out)
ok("mon_solde() : à reverser = net des paiements en ligne − dette déduite − versements", abs(float(sol["a_verser"]) - float(admin(f"select _a_verser('{D}')"))) < 0.01, out)

print("\n== 22. Soldes et versements")
expect_err("un utilisateur ordinaire ne peut pas lire les soldes", A, "select * from admin_soldes()", "acces_refuse")
rc, out, err = psql(f"select count(*) from admin_soldes() where beneficiaire_id='{D}'", user_uid=ADM)
ok("l'admin voit D parmi les soldes à reverser", out == "1", out + err)
solde = float(admin(f"select _a_verser('{D}')"))
expect_err("versement supérieur au solde refusé", ADM, f"select * from admin_enregistrer_versement('{D}',{solde + 1000},'wave','X')", "montant_invalide")
expect_err("un utilisateur ne peut pas enregistrer de versement", A, f"select * from admin_enregistrer_versement('{D}',100,'wave','X')", "acces_refuse")
expect_err("versement en espèces refusé", ADM, f"select * from admin_enregistrer_versement('{D}',100,'especes','X')", "moyen_invalide")
expect_ok("l'admin enregistre un versement partiel de 1000", ADM, f"select * from admin_enregistrer_versement('{D}',1000,'wave','WAVE-PAYOUT-1','virement semaine 1')")
ok("le solde à reverser diminue de 1000", abs(float(admin(f"select _a_verser('{D}')")) - (solde - 1000)) < 0.01)
ok("D est notifié du versement", "versement_effectue" in ntypes(D))
rc, out, err = psql("select count(*) from versements", user_uid=D)
ok("D voit son versement, A ne voit rien", out == "1" and psql("select count(*) from versements", user_uid=A)[1] == "0", out)

# commande marchande payée en ligne : 2 paiements, une seule tentative
OR5 = order_pharma()
ok("commande envoyée à une pharmacie", admin(f"select statut from delivery_orders where id='{OR5}'") == "en_attente_devis")
merchant_of = admin(f"select m.owner_id from delivery_orders d join merchants m on m.id=d.merchant_id where d.id='{OR5}'")
mu = M if merchant_of == M else M2
expect_ok("le commerçant envoie son devis (produits 3000 + livraison 500)", mu, f"select * from envoyer_devis('{OR5}','[{{\"libelle\":\"Sirop\",\"prix\":3000}}]'::jsonb,500)")
expect_ok("A valide", A, f"select * from approuver_devis('{OR5}')")
expect_ok("D accepte la livraison", D, f"select * from accept_delivery_order('{OR5}')")
expect_ok("D termine (Wave)", D, f"select * from terminer_livraison('{OR5}','wave')")
ok("2 paiements EN ATTENTE créés", pay_status(OR5) == "en_attente,en_attente", pay_status(OR5))
solde_mu_avant = float(admin(f"select _a_verser('{mu}')"))
i5, err = new_intent(A, "delivery", OR5)
ok("UNE seule tentative couvre les deux paiements (3500 FCFA)", i5 and float(i5[2]) == 3500.0, str(i5) + str(err))
confirm(i5[1], "reussi", i5[2], "W-DEL")
ok("les deux paiements sont confirmés", pay_status(OR5) == "confirme,confirme", pay_status(OR5))
ok("le solde du commerçant augmente de 95 % des produits (+2850)", abs(float(admin(f"select _a_verser('{mu}')")) - solde_mu_avant - 2850.0) < 0.01, admin(f"select _a_verser('{mu}')"))

print("\n== 23. Règlement en ligne de la dette de commission")
R12 = real_ride(D, "especes")
rc, out, err = psql("select mon_statut_chauffeur()", user_uid=D)
ok("D est de nouveau bloqué (espèces)", json.loads(out)["bloque"] is True)
expect_err("un non-chauffeur ne peut pas régler de dette", A, "select * from demander_paiement_dette('wave')", "acces_refuse")
dd, err = None, None
rc, out, err = psql("select id||'|'||ref_courte||'|'||montant from demander_paiement_dette('wave')", user_uid=D)
dd = out.split("|") if rc == 0 else None
ok("D lance le règlement en ligne de sa dette", dd is not None, err)
confirm(dd[1], "reussi", dd[2], "W-DETTE")
rc, out, err = psql("select mon_statut_chauffeur()", user_uid=D)
ok("après confirmation de l'opérateur, D est débloqué", json.loads(out)["bloque"] is False, out)
expect_err("plus de dette : rien à régler", D, "select * from demander_paiement_dette('wave')", "aucune_dette")
admin("update app_config set valeur='true' where cle='mode_test_paiements'")

print("\n== 24. Règles d'annulation (configurables)")
def assigned_ride(driver):
    rid = expect_ok("A commande une course", A, ride_call(A, "null"))
    expect_ok("D accepte", driver, f"select * from accept_ride_request('{rid}')")
    return rid
r = assigned_ride(D)
expect_ok("règle désactivée par défaut : un désistement ne suspend personne", D, f"select * from chauffeur_desiste('{r}')")
ok("D n'est pas suspendu", admin(f"select suspendu_jusqua is null from profiles where id='{D}'") == "t")
expect_ok("A annule la course", A, f"select * from annuler_course('{r}')")
admin("update app_config set valeur='2' where cle in ('desistements_chauffeur_max','annulations_client_max')")
admin(f"delete from abus_events")
r = assigned_ride(D)
expect_ok("1er désistement", D, f"select * from chauffeur_desiste('{r}')")
ok("pas encore suspendu (1 sur 2)", admin(f"select suspendu_jusqua is null from profiles where id='{D}'") == "t")
expect_ok("D reprend la même course", D, f"select * from accept_ride_request('{r}')")
expect_ok("2e désistement", D, f"select * from chauffeur_desiste('{r}')")
ok("D est suspendu automatiquement", admin(f"select suspendu_jusqua > now() from profiles where id='{D}'") == "t")
ok("D est notifié « compte_suspendu »", "compte_suspendu" in ntypes(D))
expect_err("D suspendu ne peut plus accepter", D, f"select * from accept_ride_request('{r}')", "compte_suspendu")
psql(f"update profiles set suspendu_jusqua = null where id='{D}'", user_uid=D)
ok("D ne peut pas lever lui-même sa suspension", admin(f"select suspendu_jusqua > now() from profiles where id='{D}'") == "t")
expect_err("un utilisateur ne peut pas lever une suspension", A, f"select * from admin_lever_suspension('{D}')", "acces_refuse")
ok("les statistiques comptent 1 compte suspendu", json.loads(psql("select admin_stats()", user_uid=ADM)[1]).get("comptes_suspendus") == 1)
expect_ok("l'admin lève la suspension", ADM, f"select * from admin_lever_suspension('{D}')")
expect_ok("D peut de nouveau accepter", D, f"select * from accept_ride_request('{r}')")
expect_ok("A annule après acceptation (1)", A, f"select * from annuler_course('{r}')")
r = assigned_ride(D)
expect_ok("A annule après acceptation (2)", A, f"select * from annuler_course('{r}')")
ok("A est suspendu", admin(f"select suspendu_jusqua > now() from profiles where id='{A}'") == "t")
expect_err("A suspendu ne peut plus commander", A, ride_call(A, "null"), "compte_suspendu")
expect_ok("l'admin lève aussi la suspension de A", ADM, f"select * from admin_lever_suspension('{A}')")
expect_ok("A peut de nouveau commander", A, ride_call(A, "null"))
admin("update app_config set valeur='0' where cle in ('desistements_chauffeur_max','annulations_client_max')")

print(f"\n===== RÉSULTAT : {PASS} réussis, {FAIL} échoués =====")
sys.exit(1 if FAIL else 0)
